"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

from .database import build_database_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Settings that differ between machines (local laptop, AWS EC2) are read from
# environment variables via python-decouple, which reads `backend/.env` first
# and falls back to real environment variables. `.env` is git-ignored; see
# `.env.example` for the list of variables the project expects.
# No secret is ever hard-coded in this file.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# A throwaway key is allowed for local development only. With DEBUG off (any
# real deployment) a SECRET_KEY must be supplied by the environment, so a
# misconfigured server fails loudly instead of running on a public default.
SECRET_KEY = config('SECRET_KEY', default='' if not DEBUG else 'django-insecure-local-development-only-key')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY environment variable is required when DEBUG is False.'
    )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'career',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# One switch decides the backend: DB_HOST.
#   DB_HOST empty (local laptop) -> SQLite, exactly as in Week 3.
#   DB_HOST set (EC2 on AWS)     -> PostgreSQL on Amazon RDS.
#
# Nothing about RDS — endpoint, database name, username, password — is written
# here. Those values live only in the server environment. The selection rule
# itself lives in config/database.py so it can be unit-tested without a real
# database connection.

DATABASES = {
    'default': build_database_config(
        base_dir=BASE_DIR,
        db_host=config('DB_HOST', default=''),
        db_name=config('DB_NAME', default=''),
        db_user=config('DB_USER', default=''),
        db_password=config('DB_PASSWORD', default=''),
        db_port=config('DB_PORT', default='5432'),
        db_sslmode=config('DB_SSLMODE', default='require'),
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# With DEBUG=False Django does not serve static files itself. On EC2,
# `collectstatic` copies them into STATIC_ROOT and Nginx serves that directory
# directly (see deploy/nginx/dc-intern.conf.template). This mainly affects the
# Django admin and the DRF browsable API — the React app is built separately.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# CORS
# Allows the React (Vite) frontend to call this API. Locally that is the Vite
# dev server; after deployment it will be the deployed frontend's origin, set
# through the CORS_ALLOWED_ORIGINS environment variable.
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv(),
)

# CSRF
# Django checks the Origin header on unsafe requests against this list. It is
# needed once the site is reached through a hostname other than 127.0.0.1 — for
# example the EC2 public DNS name, or a domain later. Entries must include the
# scheme, e.g. `http://ec2-1-2-3-4.compute.amazonaws.com`.
# Empty locally: Django trusts same-origin requests from ALLOWED_HOSTS anyway.

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())


# AI provider
# The backend is the only component that talks to an AI provider, so the API
# key stays server-side and never reaches the browser. `mock` means "no
# external call" — the service layer returns a structured local analysis so the
# feature is demonstrable offline and at zero cost.

AI_PROVIDER = config('AI_PROVIDER', default='mock')
AI_API_KEY = config('AI_API_KEY', default='')
AI_MODEL = config('AI_MODEL', default='mock-local')


# Running behind a reverse proxy
# On EC2, Nginx terminates the public connection and forwards to Gunicorn on
# 127.0.0.1:8000, so Django only ever sees an HTTP request from localhost. This
# tells Django to trust Nginx's X-Forwarded-Proto header when deciding whether
# the *original* request was secure — which is what makes request.is_secure(),
# and later the HTTPS settings below, work correctly.
#
# This is only safe because the header cannot be spoofed by a client: Gunicorn
# binds to 127.0.0.1 (unreachable from outside the instance) and the Nginx
# config always overwrites X-Forwarded-Proto rather than passing one through.
# If Gunicorn is ever exposed directly, this line must be removed.

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Deployment hardening
# Applied only when DEBUG is off, so local development is unaffected. These
# four are safe over plain HTTP, which is what Day 4 deploys on.

if not DEBUG:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'same-origin'
    USE_X_FORWARDED_HOST = True


# HTTPS-only hardening
# Deliberately opt-in and OFF by default. Secure cookies are never sent over
# plain HTTP, and SECURE_SSL_REDIRECT would bounce every request to a port that
# is not listening yet — so switching these on before TLS exists does not harden
# the Day 4 deployment, it breaks it (admin login and any cookie-authenticated
# request would silently fail).
#
# Set USE_HTTPS=True in the server environment on the day TLS is terminated in
# front of the application. No code change is needed.

USE_HTTPS = config('USE_HTTPS', default=False, cast=bool)

if USE_HTTPS:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
