import { useState } from 'react';
import { generateSkillGapAnalysis } from '../services/api';

// How the backend's provider metadata is described to a student. The backend
// reports what actually ran (`provider`), not what was configured, so the label
// is always truthful: a fallback response is never presented as model output.
function providerLabel({ provider, model, fallback_used: fallbackUsed }) {
  if (provider === 'bedrock') {
    return `Generated by Amazon Bedrock${model ? ` · ${model}` : ''}`;
  }
  if (fallbackUsed && provider === 'mock') {
    return 'Generated by the local rule-based analyser on the server — no AI model was used';
  }
  return `Generated by ${provider || 'the server'}`;
}

function AIRecommendationPanel({ profile }) {
  const [recommendation, setRecommendation] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    if (!profile) {
      return;
    }

    setLoading(true);
    setError('');

    try {
      // The browser only ever calls our own Django API. Django makes the AI
      // call server-side, authenticated by the EC2 instance's IAM role.
      const result = await generateSkillGapAnalysis(profile.id);
      setRecommendation(result);
    } catch (err) {
      // `err.message` is already a written-for-users message from api.js —
      // never a stack trace, a server traceback, or an AWS error payload.
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section className="card">
      <h2>5. AI Recommendation</h2>
      <p className="hint">
        Generates a skill gap analysis from the profile, skills, and career inputs saved
        for this student.
      </p>

      {!profile && (
        <p className="message message-info">
          Save a student profile first — the analysis needs a profile to work from.
        </p>
      )}

      <button
        type="button"
        className="btn"
        onClick={handleGenerate}
        disabled={!profile || loading}
      >
        {loading ? 'Generating analysis…' : 'Generate Skill Gap Analysis'}
      </button>

      {/* aria-live so a screen reader announces the state change, and a visible
          spinner so a slow model call does not look like a frozen page. */}
      <div aria-live="polite">
        {loading && (
          <p className="message message-info loading-row">
            <span className="spinner" aria-hidden="true" />
            Generating your analysis. This usually takes a few seconds — please keep this
            page open.
          </p>
        )}

        {error && !loading && (
          <p className="message message-error">
            {error}{' '}
            <button type="button" className="link-btn" onClick={handleGenerate}>
              Try again
            </button>
          </p>
        )}
      </div>

      {recommendation && !loading && (
        <div className="recommendation">
          <h3>{recommendation.recommendation_type}</h3>

          <p className="hint">
            {new Date(recommendation.created_at).toLocaleString()} ·{' '}
            {providerLabel(recommendation)}
          </p>

          {recommendation.fallback_used && recommendation.provider === 'mock' && (
            <p className="message message-info">
              This analysis was produced on the server without an AI model. It follows the
              same structure, but it is rule-based rather than model-generated.
            </p>
          )}

          {recommendation.notes?.map((note) => (
            <p className="message message-info" key={note}>
              {note}
            </p>
          ))}

          {/* white-space: pre-wrap keeps the section breaks and indentation the
              backend produced, so the eight sections stay readable. */}
          <pre className="recommendation-content">{recommendation.content}</pre>

          <p className="message message-info disclaimer">
            <strong>AI-assisted guidance — please review.</strong> This analysis is
            generated from what you entered and may be incomplete or wrong. It cannot
            verify your skills and is not a guarantee of an internship or a job. Discuss it
            with a lecturer, mentor, or supervisor before acting on it.
          </p>
        </div>
      )}

      <p className="hint hint-note">
        Recommendations are generated by the backend. Locally that is a rule-based mock;
        on the deployed server it is Amazon Bedrock. Either way, the browser never handles
        an AI credential — the response tells you which one produced the text.
      </p>
    </section>
  );
}

export default AIRecommendationPanel;
