# Generated by Django 6.0.7 on 2026-07-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Information Systems', 'Information Systems'), ('Cybersecurity', 'Cybersecurity'), ('Data Science', 'Data Science'), ('Computer Engineering', 'Computer Engineering'), ('Other IT Related Field', 'Other IT Related Field')], max_length=50)),
                ('year_of_study', models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4'), ('Final Year', 'Final Year')], max_length=20)),
                ('career_interest', models.CharField(max_length=255)),
                ('internship_goal', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Web Development', 'Web Development'), ('Database', 'Database'), ('Cloud Computing', 'Cloud Computing'), ('Cybersecurity', 'Cybersecurity'), ('AI and Data', 'AI and Data'), ('Networking', 'Networking'), ('Software Engineering', 'Software Engineering'), ('Professional Skills', 'Professional Skills'), ('Other', 'Other')], max_length=50)),
                ('confidence_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='career.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('Skill Gap Analysis', 'Skill Gap Analysis'), ('Career Path', 'Career Path'), ('Project Recommendation', 'Project Recommendation'), ('Learning Plan', 'Learning Plan'), ('Resume Feedback', 'Resume Feedback'), ('Placeholder', 'Placeholder')], max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='career.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CareerInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('Resume Text', 'Resume Text'), ('Career Goal', 'Career Goal'), ('Internship Goal', 'Internship Goal')], max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_inputs', to='career.studentprofile')),
            ],
        ),
    ]
